services:
  expense-tracker:
    container_name: expense-tracker
    ports:
      - "${LOCAL_DK_SERVER_PORT}:${LOCAL_DK_SERVER_PORT}"
    networks:
      - expense-network
    image: expense-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .\.env
    depends_on:
      - expense-tracker-db

  expense-tracker-db:
    container_name: ${LOCAL_DK_HOST_NAME}
    ports:
      - "${LOCAL_DK_DB_SERVER_PORT}:27017"
    networks:
      - expense-network
    image: mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - expense-volume:/data/db

networks:
  expense-network:
    name: expense-tracker-network
    driver: bridge

volumes:
  expense-volume:
    name: expense-tracker-volume


